"""empty message

Revision ID: 42739551fd0f
Revises: 338784d56258
Create Date: 2024-07-16 23:42:09.441469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '42739551fd0f'
down_revision: Union[str, None] = '338784d56258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
